"""
Django settings for hilfling_image_proxy project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

print(BASE_DIR)

env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")  # reads your .env file


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.staticfiles',
    'django.contrib.contenttypes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
]

# Disable database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.dummy',
    }
}


ROOT_URLCONF = 'hilfling_image_proxy.urls'

WSGI_APPLICATION = 'hilfling_image_proxy.wsgi.application'


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

PROXY_TARGET_URL = env("PROXY_TARGET_URL")
IMAGE_STORAGE_PATH = env("IMAGE_STORAGE_PATH", default="media")
IMAGE_BASE_URL = env("IMAGE_BASE_URL", default="/media")

# Backend JWKS endpoint
JWKS_URL = env("JWKS_URL", default=f"{PROXY_TARGET_URL}/.well-known/jwks.json")
